[package]
name = "wasi-rdbms"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/wasi-rdbms"
description = "WIT definitions and WASI RDBMS"

[lib]
path = "src/lib.rs"
