name: CI
on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cargo-bins/cargo-binstall@main
      - name: Validate WIT
        run: |
          cargo binstall --no-confirm wasm-tools@1.210.0
          wasm-tools component wit -vv wit
